-- How to create table using sql

CREATE TABLE EMPLOYEE
(
  EMP_ID INT PRIMARY KEY,
  EMP_NAME VARCHAR(20) NOT NULL,
  EMP_CITY VARCHAR(20) NOT NULL,
  EMP_SALARY INT NOT NULL
);

-- Insert data in table
INSERT INTO EMPLOYEE (EMP_ID,EMP_NAME,EMP_CITY,EMP_SALARY) VALUES (101,'Alice','Mumbai',14000);

INSERT INTO EMPLOYEE (EMP_ID,EMP_NAME,EMP_CITY,EMP_SALARY) VALUES (102,'Bob','Bengaluru',200000);

-- show table data


SELECT * FROM EMPLOYEE;  -- Use to select all data in table.

SELECT EMP_NAME,EMP_CITY FROM EMPLOYEE; 


